apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: client
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/pontep/client
      #  externalTrafficPolicy: Cluster
      #containerPorts:
      #  - port: 8080
      #    protocol: TCP
      #    targetPort: 8080
      #  selector:
      #    app: client
      #  sessionAffinity: None
      #  type: LoadBalancer 
