apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdk8splus-chart-demo-pod-3cc43756
spec:
  replicas: 1
  selector:
    matchLabels:
      cdk8s.deployment: cdk8spluschartdemo1733F303
  template:
    metadata:
      labels:
        cdk8s.deployment: cdk8spluschartdemo1733F303
    spec:
      containers:
        - env: []
          image: paulbouwer/hello-kubernetes:1.8
          name: main
          ports: []
          volumeMounts: []
      volumes: []
