apiVersion: v1
kind: Service
metadata:
  labels:
    app: source
  name: source
  namespace: b6000783
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: source
  sessionAffinity: None
  type: ClusterIP
